# .github/config.yml
# Purpose: Configure GitHub Codex (indexing + AI visibility)
# Ensures CRT repo JSON + HTML are discoverable and refreshed automatically.
# ---------------------------------------------------------------------------

codex:
  include:
    # Include all content and structured data used by CRT
    - "items/**/*.json"
    - "items/**/*.txt"
    - "items/**/*.md"
    - "docs/**/*.json"
    - "docs/**/*.html"
    - "docs/**/*.xml"
    - "docs/**/*.txt"
  exclude:
    # Exclude build caches, node modules, temp, and backup dirs
    - "node_modules/**"
    - "tmp/**"
    - "dist/**"
    - "sandbox/**"
    - "backup/**"
    - "*.bak"
  reindex_interval: 30m
  max_file_size_mb: 5
  enable_ai_search: true
  enable_json_embeddings: true
  enable_yaml_support: true
