# .github/config.yml
# Purpose: Nudge indexing to include CRT’s data & outputs (safe, public).

codex:
  include:
    - "items/**/*.json"
    - "items/**/*.ndjson"
    - "items/**/*.yaml"
    - "items/**/*.yml"
    - "items/**/*.txt"
    - "items/**/*.md"
    - "docs/**/*.json"
    - "docs/**/*.ndjson"
    - "docs/**/*.yaml"
    - "docs/**/*.yml"
    - "docs/**/*.html"
    - "docs/**/*.xml"
    - "docs/**/*.txt"
  exclude:
    - "node_modules/**"
    - "tmp/**"
    - "dist/**"
    - "sandbox/**"
    - "backup/**"
    - ".vscode/**"
    - ".idea/**"
    - ".DS_Store"
    - "*.bak"
    - "*.map"
  reindex_interval: 30m
  max_file_size_mb: 5
  enable_ai_search: true
  enable_json_embeddings: true
  enable_yaml_support: true
