# .github/copilot.yml
# Purpose: Help GitHub Copilot / AI interpret the ClearRound datasets repo.
# No secrets here—safe to keep public.

schema:
  languages:
    - json
    - yaml
    - html
    - xml
    - markdown

  include:
    - items/            # source datasets (content/events/venues/images/runners/...)
    - docs/             # generated outputs (blogs, indexes, rss, sitemap, manifest)
    - .github/          # repo metadata/config for AI context
  exclude:
    - node_modules/
    - tmp/
    - dist/
    - sandbox/
    - backup/
    - "*.bak"

  # Folder semantics help Copilot reason about relationships
  semantics:
    items/: "Source-of-truth structured data for content, events, venues, images, and runner configs."
    items/triggers/: "Launch JSONs that point to content/events/images and kick off publication."
    items/runners/: "Structure Runner (expeditor) and policy/instruction files that transform items → docs."
    docs/: "Published, static site artifacts (HTML pages, RSS, sitemap, blog manifests)."
    docs/blogs/: "Per-post folders with index.html and corresponding *-publish.json."

assistant:
  mode: documentation
  guidance: |
    - Maintain separation of concerns: items = READ, docs = WRITE, blog = PUBLISH.
    - When generating examples, follow the 'post page + publish.json' pattern for runner output.
    - Treat global indexes (blogs index, year index, rss, sitemap, manifest) as scheduled artifacts.
    - Prefer paths under docs/blogs/<brand>-blogs-<year>/<post-folder>/.

  indexing:
    frequency: 30m
    context_depth: 3

metadata:
  maintainer: "ClearRound Travel"
  version: "2025-10-14"
  repo_role: "datasets + publishing pipeline (CRT Structure Runner)"
