# .github/copilot.yml
# Purpose: Help Copilot understand CRT's lanes and file roles (safe to keep public).

schema:
  languages: [json, yaml, html, xml, markdown]
  include:
    - items/            # source datasets
    - docs/             # published outputs
    - .github/          # repo config for AI context
  exclude:
    - node_modules/
    - tmp/
    - dist/
    - sandbox/
    - backup/
    - ".DS_Store"
    - ".env"
    - "*.bak"

  # Folder semantics sharpen AI reasoning about relationships
  semantics:
    items/: "Source-of-truth structured data."
    items/content/: "Blog source JSON (read-only)."
    items/events/: "Event metadata JSON."
    items/venues/: "Venue metadata JSON."
    items/images/: "Hero/card image descriptors."
    items/runners/: "Structure Runner + instruction/policy/openapi."
    items/triggers/: "One-URL JSON triggers that kick off publication."
    docs/: "Published static artifacts (HTML, RSS, sitemap, manifest)."
    docs/blogs/: "Per-post folders (index.html + *-publish.json)."

assistant:
  mode: documentation
  guidance: |
    - Keep lanes: items = READ, docs = WRITE, blog = PUBLISH.
    - Runner outputs exactly two files per post: *-publish.json + index.html.
    - Global indexes (blogs index, year index, RSS, sitemap, manifest) are scheduled artifacts.
    - Prefer paths: docs/blogs/<brand>-blogs-<year>/<post-folder>/
  indexing:
    frequency: 30m
    context_depth: 3

metadata:
  maintainer: "ClearRound Travel"
  version: "2025-10-15"
  repo_role: "datasets + publishing pipeline (CRT Structure Runner)"
