name: "Add Show (Auto)"
description: "Paste the official site. Optionally add start date + series/championship flags."
title: "auto-meta"
labels: ["task:meta-auto"]
body:
  - type: input
    id: official_url
    attributes:
      label: Official website URL (required)
      placeholder: "https://www.ushja.org/programs/ihdc/championship"
    validations:
      required: true

  - type: input
    id: official_start_date
    attributes:
      label: Official start date (YYYY-MM-DD)
      placeholder: "2025-08-15"
    validations:
      required: false   # set to true if you decide to require it later

  - type: dropdown
    id: is_series
    attributes:
      label: Is this part of a series?
      options: ["No","Yes"]
      default: 0

  - type: input
    id: series_week
    attributes:
      label: Series week number (optional if series)
      placeholder: "4"

  - type: dropdown
    id: is_championship
    attributes:
      label: Is this a championship?
      options: ["No","Yes"]
      default: 0

  - type: input
    id: championship_type
    attributes:
      label: Championship type (optional, e.g., pony, junior, equitation)
      placeholder: "pony"
