name: "Enrich Show (Auto)"
description: "Fill venue, dates, and proper title from the official link stored in meta.json."
title: "enrich-meta"
labels: ["task:meta-enrich"]
body:
  - type: input
    id: show_slug
    attributes:
      label: Show slug (required)
      placeholder: "hampton-classic"
    validations:
      required: true
  - type: dropdown
    id: crawl_depth
    attributes:
      label: Crawl depth
      options: ["1 (homepage only)","2 (follow likely links: schedule/dates/venue/directions)"]
      default: 1
